### ISSUE TITLE
Avoid very small edit box

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-edit#12]
Edit box width is relative to text region initially highlighted.

This can sometimes  result in edit boxes that are too small.
Maybe have a fixed 65% of image (ie manuscript page) width edit box?

Lookihere: Acceptance criteria with a check box :)

- [x] Make sure minimum width and height of edit box is not too small. At least shows the edit box, buttons and the appropriate lines of the transcription (ie lines that are highlighted on the image)

**Comment by kansallisarkisto** [comment]
I have now written (and will soon push) code which calculates the width of text for other purposes. How about reusing that so that the width of the edit box = the length of the longest line? Possibly also so that the box grows as the longest line grows? Some users requested that.

**Comment by kansallisarkisto** [comment]
I'm working on enlarging the box according to line length and will also ensure that all the buttons fit on one line, which was reported as #31

**Comment by cziaarm** [comment]
URL https://transkribus.eu/readTest/edit/correct/2305/23316/1?tco=0&view=i
chrome 60.0.3112.101 
firefox 45.0.2

Width seems reasonable but it appears that the height of the edit box is less than it should be:

![twi-edit-18.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58765b75e090f815004aac84/125516c66e82c728ace21e0d46fc83936e8787a09ba4ee1be611b2843b492d762a10e17132d0ba79bb152c50590d1dfe47505d44fcfedc2ff3b03923d84e17ff933c0120996048e6edc00db513bb228b4d80bcbd8f4cc3e83b20ef828b4d3e1d1755.png)

Steps taken were to click on a small word on the image before any others.

**Comment by cziaarm** [comment]
https://transkribus.eu/readTest/edit/correct/2305/23314/1

**Comment by kansallisarkisto** [comment]
Both width and height should be ok now.

**Comment by cziaarm** [comment]
I made some acceptance criteria for this issue (belatedly). It has a checkbox! Latest deployment now passes those acceptance criteria when testing against the case highlighted above.
