### ISSUE TITLE
Styling buttons for edit window

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-edit#14]
Access the style related tags with buttons in edit box in the fashion of common text editoing apps (eg bold, underline etc)

**Comment by kansallisarkisto** [comment]
Please explain more. What's the equivalent in the expert client?

**Comment by hackmanschorsch** [comment]
![editor_screenshot](https://user-images.githubusercontent.com/16098955/27023994-3b3f8f5e-4f55-11e7-8de8-2474fb02ea03.PNG)
In expert client we have: (bold, italic, subscript, superscript, underlined, strikethrough) as textstyle tags. They are stored as usual tags (in the custom tag attribute) but of course are handled a little bit different.
