### ISSUE TITLE
"Correction Interface" should also act as a viewer with an "Edit" button

### ISSUE THREAD

**Issue by kansallisarkisto** [Transkribus/TWI-edit#17]
"Correction Interface" should have an "Edit" button. The button should be grayed out when the document lacks a segmentation and thus cannot be transcribed. Clicking the button should instruct the user to create a segmentation for the document using the expert client.

**Comment by cziaarm** [comment]
This looks to be done as a sort of duplicate of  Transkribus/TWI-mc#44 and Transkribus/TWI-edit#17
