### ISSUE TITLE
"Sometimes" a tag starting from the beginning of a line does not change correctly when entering text

### ISSUE THREAD

**Issue by kansallisarkisto** [Transkribus/TWI-edit#18]
If text is input in the beginning of a line and a tag starts there, it sometimes grows and sometimes moves. The tag should always move.

**Comment by kansallisarkisto** [comment]
I fail to replicate this now. Could solving some of the other bugs related to caret positioning have solved this?

**Comment by cziaarm** [comment]
I have tested this on the following page:

https://transkribus.eu/readTest/edit/correct/2305/23316/1?tco=0&view=i

I opened the edit box and tagged a word (at the beginning of the line) I then added some more text at the beginning of the same line. There was no unexpected movement or growth of the tag.

Screenshot:

![twi-edit-18.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58765b75e090f815004aac84/125516c66e82c728ace21e0d46fc83936e8787a09ba4ee1be611b2843b492d762a10e17132d0ba79bb152c50590d1dfe47505d44fcfedc2ff3b03923d84e17ff933c0120996048e6edc00db513bb288a4687bcbd8f4cc3e83b20e38a874f391c1755.png)

**Comment by cziaarm** [comment]
btw tested in chrome 60.0.3112.101
