### ISSUE TITLE
Pages > 1 give NoneType' object has no attribute 'get' error

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-edit#2]
Example URL: http://127.0.0.1:8003/edit/correct/1/28/7, https://transkribus.eu/readTest/edit/correct/1/28/7
Browsers: firefox, chrome

This is thrown by the templatetag get_item which is being called here:

In template /home/cziaarm/READ/mc/apps/edit/templates/edit/correct.html, error at line 102

**Comment by kansallisarkisto** [comment]
I need permission to access that so that I can take a look.

**Comment by cziaarm** [comment]
I am not an owner... @kahlep @hackmanschorsch please give @kansallisarkisto access to ts Ground Truth (id=1)

**Comment by hackmanschorsch** [comment]
@kansallisarkisto has access now

**Comment by kansallisarkisto** [comment]
Fixed. The cause wasn't the page no. The example just had empty lines, which weren't handled properly.
