### ISSUE TITLE
Right click to show the tag menu does not move the caret correctly

### ISSUE THREAD

**Issue by kansallisarkisto** [Transkribus/TWI-edit#20]
Right-clicking to show the tag menu leaves the caret where it was and afterward when clicking to hide the menu, the caret does not show up where you expect it to.

**Comment by jupouta** [comment]
After clicking to hide the tag menu, the cursor still goes to the beginning of the chosen line

**Comment by kansallisarkisto** [comment]
Which browser(s) are you testing with?

**Comment by jupouta** [comment]
Both Chrome and Firefox do that

**Comment by cziaarm** [comment]
-[] test checklist

**Comment by cziaarm** [comment]
This sill appears to be happening in ie/chrome/ff

To reproduce. 

- Open edit box left click and note the cursor position.
- Right click to bring up the  tag menu
- left click on the edit box again to close the tag menu
- Cursor/caret  is at the start of the line

Expected result:  Cursor to be where the left was made in the edit box (or as near as is reasonable)

**Comment by cziaarm** [comment]
@kansallisarkisto to take control of caret display to help with these sorts of issues

**Comment by cziaarm** [comment]
@kansallisarkisto  caret issues: #74, #20, #34 potentially can be "lived with" for this iteration and handled in subsequent iterations
