### ISSUE TITLE
Fix canvas in Image view.

### ISSUE THREAD

**Issue by jnphilipp** [Transkribus/TWI-edit#24]
Fix the canvas in the Image interface.
* fix height to screen height
* stop moving the image out ot the canvas.

**Comment by jnphilipp** [comment]
The [containment feature from jquery](https://jqueryui.com/draggable/#constrain-movement) doesn't work here due to zooming. 

Also there is a button to reset the image.

**Comment by cziaarm** [comment]
reset image button is a possible workaround

**Comment by jnphilipp** [comment]
Should be done with #60.
