### ISSUE TITLE
Styling buttons on Line by line interface.

### ISSUE THREAD

**Issue by jnphilipp** [Transkribus/TWI-edit#25]
Add the styling buttons from input window and #14 on each line. Show only on the current selected line.

**Comment by hackmanschorsch** [comment]
Styling needs no underlined text

**Comment by jnphilipp** [comment]
You mean the lines like the other tags?

**Comment by hackmanschorsch** [comment]
Yes. For example if you mark a word and say it's 'italic' then the user sees it in italic but there is no need to underline the word with a black line.

**Comment by jnphilipp** [comment]
Okay, I'll remove them. I only put them there because they are in the expert client.

**Comment by cziaarm** [comment]
Hi @jupouta please test the styling buttons for the line-by-line interface are funcitoning correctly.

Thanks,

Rory

**Comment by cziaarm** [comment]
for info I have raised #42 which is related to line-by-line but not quite covered by this issue
