### ISSUE TITLE
Line by line: New line activated but text goes to the previous one

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TWI-edit#26]
Steps to reproduce: Start correcting a line, then change to the next line by clicking the tabulator key. Although the new line is marked as the current line and even the horizontal cursor is visible the text is not written there. Also changing the line with the mouse clicking on the very first position brings this behavior but not always. If the mouse click is near enough the first character then everything works fine.
Again tested on Firefox 54.0.1 (32-Bit).

**Comment by jnphilipp** [comment]
This is part of the general problem with the caret position. #10 #20 #21

**Comment by maxbry** [comment]
When clicking in a line, typing something, pressing tab and then typing again:
- in firefox nothing happens
- in chrome, the is inserted in the previously selected line

**Comment by maxbry** [comment]
BTW: I tested this on readTest, so maybe that server doesn't have your fix yet..
