### ISSUE TITLE
Line by line: Tag continues in the next line

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TWI-edit#28]
What if tag is continued in the next line? E.g. person firstname (in the first line), lastname (in the second line)
Suggestion: In the tag list you can set the tag attribute continued = true for the second tag. (This is an already used attribute for tags in Transkribus)

**Comment by jnphilipp** [comment]
The continued attribute is already supported. The problem with the Line by line is a selection problem. Since it is impossible to select more than a single line. To do this one has to use a different editing interface where it is possible.

**Comment by hackmanschorsch** [comment]
Okay understand - my point was that the user could have a 'continued' flag to choose (e.g. as an option in the right click menu). This way he could mark a tag in the second line to be the continued tag of the tag in the first line. But may we just keep this in mind as an option for the future.
