### ISSUE TITLE
unexpected highlighting for side by side regions

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-edit#3]
url: https://transkribus.eu/readTest/edit/correct/3/332/4
browsers: chrome firefox

when hovering over the text on the left the text on the right is sometimes hilighted.

also when clicking on the text on the right, the edit box is initiated for a line from the text on the left.

**Comment by kansallisarkisto** [comment]
Please give me access to that collection or a link to a different one where I can reproduce the problem.

**Comment by cziaarm** [comment]
I am but a simple transcriber for this collection :( @hackmanschorsch @kahlep  can you help @kansallisarkisto out with this?

**Comment by kansallisarkisto** [comment]
Fixed. Line ids prefixed with region ids to be unique.
