### ISSUE TITLE
Line numbering in different text regions

### ISSUE THREAD

**Issue by jnphilipp** [Transkribus/TWI-edit#30]
In the moment multiple lines with number 1 are there, due to different text regions, but with no clear distinguishen.

**Comment by GuenterMuehlberger** [comment]
To be honest I do not like line numbers anyway I find them disturbing at that place. They are fine if I have no link to the line image  (in book publications) but not in the digital world.

**Comment by GuenterMuehlberger** [comment]
Line numbers disappeared, but the behavioour of the box is now different. It opens sometimes just showing the first line or half of it. Suggestion: The box should always open with just ONE line selected - the one which I selected  (the green line). If the user wants to see more than one line than he can use + and -.

**Comment by cziaarm** [comment]
Numbers removed
