### ISSUE TITLE
Increase box width

### ISSUE THREAD

**Issue by maxbry** [Transkribus/TWI-edit#31]
When opening the edit box in the edit->image interface, the box is slightly to narrow to fit all the buttons in one line

**Comment by maxbry** [comment]
![readtest_box](https://user-images.githubusercontent.com/8791965/29061667-17881c4c-7c1f-11e7-9a4b-b93a503e95ec.png)

**Comment by kansallisarkisto** [comment]
This problem overlaps with #12 and should be fixed at the same time. I'm working on #12 and will do it.

**Comment by kansallisarkisto** [comment]
The box size now grows when its contents do.

**Comment by kansallisarkisto** [comment]
Both width and height should be ok now.
