### ISSUE TITLE
Typing combining characters: Cursor jumps to beginning/different line

### ISSUE THREAD

**Issue by thodel** [Transkribus/TWI-edit#34]
When typing combining character/diacritical mark (i.e. grave accent, U+0300), cursor jumps to the beginning of the line/the top line visible and text is inserted there.

**Comment by kansallisarkisto** [comment]
Please specify which browser you're using whenever you report bugs.

When testing input with Firefox, there's a problem with accents as well. The same character is input with and without the accent (and not saved in the array precisely as shown either, it seems). 

This is a (kind of) regression. keydown/keyup/keypress (or the lack thereof) has caused issues before (some of which have been very browser dependent). At least in Firefox this used to work really well and seemed to work in Chromium too but evidently something has happened to both.

**Comment by thodel** [comment]
sorry for missing spec.:
60.0.3112.90 (official Build) (64-Bit)

**Comment by cziaarm** [comment]
@kansallisarkisto  caret issues: #74, #20, #34 potentially can be "lived with" for this iteration and handled in subsequent iterations
