### ISSUE TITLE
Edit interface Save button doesnt work

### ISSUE THREAD

**Issue by yuoiea** [Transkribus/TWI-edit#36]
When I enter text and click save and refresh the page -> the text is disappeared. Makes the whole edit-interface unsusable.

**Comment by kansallisarkisto** [comment]
Once again, please be more elaborate. I cannot reproduce this.

**Comment by kansallisarkisto** [comment]
Once again, please be more specific when you report a bug and state exactly what you did and what your environment is (browser and version). I did some testing and evidently this only happens with the save button at the top of the viewer whilst the save button in the edit box works.

**Comment by yuoiea** [comment]
Firefox 54.0.1 and Pale Moon 27.4.1. Used the save button which was next to "Page status" dropdown.

**Comment by kansallisarkisto** [comment]
I've studied this some more. Neither save button is actually broken but when the dialog is open, the button on the page itself just responds slower. Hence what I suspect happened is that the testing user clicked save and then refreshed the page too soon afterward. That is, before the message stating that the changes have been saved. I will instead add a message warning users when (1) saving is in progress and (2) when they might be discarding changes unintentionally. The latter is a separate feature and I'll open an issue about it later.

**Comment by kansallisarkisto** [comment]
I have done what I said above that I would do.
