### ISSUE TITLE
Adding line in edit interface brokes the input box

### ISSUE THREAD

**Issue by yuoiea** [Transkribus/TWI-edit#37]
When I add multiple rows and browse down and up again the header bar of the input box disappeares -> i can't move or close the box anymore.

**Comment by kansallisarkisto** [comment]
Could you please be more elaborate. Also state which browser and what version you're using. Otherwise I can't reproduce this.

**Comment by yuoiea** [comment]
Firefox 54.0.1 and Pale Moon 27.4.1. Try following:
- Select a line
- Click add line couple times
- Browse to bottom line (using keyboard "down" button)
- Browse to top line (using keyboard "up" button)
-> cannot move or close input box because the header bar isn't visible anymore

**Comment by kansallisarkisto** [comment]
I just did work on improving how the dialog size is set. My work changed precisely how the size is set and even though I wasn't aware of this particular bug when I did it, the improved solution has probably resolved this too since I cannot reproduce it. Labeling accordingly but please do let me know if it reappears.

**Comment by yuoiea** [comment]
No iI can grab the window and move it but the box header is missing so i can't close the box (except "esc"). See screenshot
![heared missing.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5948fad5ba820b001a59ce91/125516c66e82c728ace21e0d46e0919b318787e982e0ac50ad53f7d665043761260ea62864c7b96aea1b2a0558584faa130b0d42f4fb892ba1e338258c5958bfc3714d36976345f3e5db55ea43a82a994c84bcbd8f4cc3eb3421e58c8c4937191755.png)

**Comment by kansallisarkisto** [comment]
I've done even more rewriting of the code for setting the size. Those changes affected the header in particular and I can no longer reproduce this so I have to ask you to test once again.
