### ISSUE TITLE
Versioning of save action missing

### ISSUE THREAD

**Issue by EvaMLang** [Transkribus/TWI-edit#38]
![2017-08-16_webui_versioning](https://user-images.githubusercontent.com/17451573/29364515-02178340-8294-11e7-8696-b7fe5e84085a.PNG)
Transkribus allows references to the parent version of the currently saved document - see screenshot (entry line labelled as "NEW" was a "Save changes" on the edit webinterface). When saving from webUI, the parent ID is lost, creating a new version for each save.

Please add the parent ID before saving to the database.

**Comment by EvaMLang** [comment]
Seems like I am not allowed to assign resposible developers on this repo - can someone please take care of this (giving me github rights / assigning people)? Thanks

**Comment by kahlep** [comment]
Hi Eva, I just modified your access rights. Can you try again to assign the issue?

**Comment by EvaMLang** [comment]
@kahlep thank you, I can now assign, yay!

**Comment by cziaarm** [comment]
@hackmanschorsch to look at how the version is integrated between TWI and REST

**Comment by hackmanschorsch** [comment]
The rest service 'postPageTranscript' has the QueryParam 'parent' where you hand over the parentID to the server.
@jnphilipp @kansallisarkisto  please use this param when saving the transcripts from the webUI to keep the history of the transcripts

**Comment by cziaarm** [comment]
@hackmanschorsch What is the parent in this context? The page, the doc, the collection, something else?

**Comment by hackmanschorsch** [comment]
With parent the transcript ID is meant. So if you load the current (latest) transcript for editing you have to read the tsid from the transcript metadata and hand it as parent in the save method. This is for keeping the history of each transcript version.

**Comment by hackmanschorsch** [comment]
Saving the parent ID works now fine! But the status was reset to 'NEW' instead of keeping the previous status 'InProgress'.

**Comment by hackmanschorsch** [comment]
So my suggestion would be to always keep the current status during saving and adding the logic at the server side.

**Comment by cziaarm** [comment]
OK so a known issue and a server fix for mc-v0.04 ?

**Comment by hackmanschorsch** [comment]
I'm not sure. 

Please check if the status of the transcript you send to the server is null!

Then we change it either from 'NEW' to 'InProgress' or keep the old status automatically. But this works not if the status is implicitely set to 'NEW' or some other status.
