### ISSUE TITLE
Notification if changes not saved

### ISSUE THREAD

**Issue by jupouta** [Transkribus/TWI-edit#39]
It would be good if there was a notification when the user is changing the page or leaving the edit interface if there have been any changes in the text (if e.g. the user has forgotten to save the changes).

**Comment by kansallisarkisto** [comment]
Yes. Such a feature existed at one point but some UI redesign removed it. Time to update it.

**Comment by kansallisarkisto** [comment]
The warning about unsaved changes is back. Additionally, the default browser warning about unsaved changes is now shown when navigating away from the page or refreshing it.

**Comment by cziaarm** [comment]
related to Transkribus/TWI-edit#44 ?
