### ISSUE TITLE
Layout improvements

### ISSUE THREAD

**Issue by GuenterMuehlberger** [Transkribus/TWI-edit#41]
I have drafted a paper with a lot of small and some heavier improvements for the WebUI. I think that Nathaniel and Max could maybe work on this. There are some deeper issues included which may be handled separately.

**Comment by GuenterMuehlberger** [comment]
[Layout improvements.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/598b061fda729505ca087b29/125516c66e82c728ace21e0d46c495832c9797e986e4af51ab4bf5992c4833606b48e13b628ae92dbc56395b4d5a47ad155f0e4dadacdb7ff3b234708a5b0fe5826a597dc72f0dbefad341eb5ee779c11ac7a4b6984dc8e93427ed8a8a4f3d1e031c8afb5536a99f5985.docx)

**Comment by maxbry** [comment]
I would consider this issue done since most of its requirements are done or have been changed.
