### ISSUE TITLE
View mode adjustments

### ISSUE THREAD

**Issue by maxbry** [Transkribus/TWI-edit#46]
* document title in the breadcrumb should be a link to the default view of the document
* Standard size of the shown image should be height, not width
* unneeded buttons in view mode should be grayed out
* Menue Bar
** At the very left:
*** the i Button 
*** Image / LinebyLine /SidebySide/ Text: put them to the left
*** Forward, and page number etc.: Make it much smaller and put it exactly in the centre; put zoom in out and centre besides
** Add: adjust to height, adjust to width and use much smaller buttons
** On the right hand side:
*** “Edit” button, Save changes button, Page status

**Comment by cziaarm** [comment]
* - [ ] document title in the breadcrumb should be a link to the default view of the document
* - [ ] Standard size of the shown image should be height, not width
* - [ ] unneeded buttons in view mode should be grayed out
* - [ ] Menu Bar
  * - [ ] At the very left:
    * - [ ] the i Button 
    * - [ ] Image / LinebyLine /SidebySide/ Text: put them to the left
    * - [ ] Forward, and page number etc.: Make it much smaller and put it exactly in the centre; put zoom in out and centre besides
  * - [ ] Add: adjust to height, adjust to width and use much smaller buttons
  * - [ ] On the right hand side:
    * - [ ] “Edit” button, Save changes button, Page status

**Comment by cziaarm** [comment]
@cziaarm will pick up 

- [ ] document title in the breadcrumb should be a link to the default view of the document
