### ISSUE TITLE
Edit line box shows up too small

### ISSUE THREAD

**Issue by jupouta** [Transkribus/TWI-edit#47]
I open the edit interface, then choose a line to transcribe, but get this:
![kuva](https://user-images.githubusercontent.com/16373538/29810202-b75024b6-8ca7-11e7-870e-94d628fe1141.png)

Happens both on Firefox and on Chrome, apparently when no transcriptions have been made on the page.

**Comment by kansallisarkisto** [comment]
The width issue seems to be resolved when I rewrote things. Height is still a problem but I'm working on that.

**Comment by kansallisarkisto** [comment]
The problem still persists in some cases, removing this label.

**Comment by kansallisarkisto** [comment]
Both width and height should be ok now.

**Comment by cziaarm** [comment]
I think there has been some regression as I closed Transkribus/TWI-edit#12 after confirming the example I reported was OK. I will close this one as I have opened Transkribus/TWI-edit#54 and assigned all the TWI-edit people to help deal with the regression issues.
