### ISSUE TITLE
Thumbnail view is not showing last page

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TWI-edit#49]
If I open the first project in the crowdProjectTestCollection with 7 pages (or any other) only 6 pages are shown in the thumbnail view. Only when opening the 7th page directly it gets shown in the thumbnails.
![unbenannt](https://user-images.githubusercontent.com/16098955/30112230-da244ef8-9310-11e7-8ecc-d2cac5ed37f1.PNG)

**Comment by kansallisarkisto** [comment]
A change a while ago broke this but it's fixed now. Enjoy!

**Comment by hackmanschorsch** [comment]
Now works if thumbs fit in the first thumb overview - but if there are more thumbs and you have to scroll to the next view then still one page is missing at the end.
See: https://transkribus.eu/readTest/view/2305/23217/1#

**Comment by hackmanschorsch** [comment]
works fine for this example now
