### ISSUE TITLE
Small edit box is back

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-edit#54]
For steps to reproduce see Transkribus/TWI-edit#53
![return_of_dreaded_small_edit_box.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58765b75e090f815004aac84/125516c66e82c728ace21e0d46fa918e36908d9680ef8047b658f1902c4218602405af274f80e721ab7d790e174d52be011a001ea9aacd39aca439798b080cead06b0d27943b19aeb88218ea05ef268e1cd7a4a0980e91b6697abad2c51a7c0c0f0a88f95734a5994ec95df74ce94d51a314242e.png)

- [ ] un-regress (?) the earlier fix for edit box being too small Transkribus/TWI-edit#12 and Transkribus/TWI-edit@b6634c3

**Comment by kansallisarkisto** [comment]
Having tested a number of other things, I've had to conclude that this can still happen but the situations are rare. I can't pinpoint it yet but it seems to be related to how spaces were saved in the past and gets fixed if a document is saved again.

**Comment by kansallisarkisto** [comment]
Sigh. I found at least one more case in which this happens but it's fixed locally now. Commit coming soon to a git repository near you!
