### ISSUE TITLE
Pressing edit button should select first line

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TWI-edit#59]
And the edit box opens already without searching for the first line (mainly to help users to easily start with editing)

**Comment by hackmanschorsch** [comment]
Can't test this at the moment since the 'Edit' button and 'Save changes' button are currently not selectable.

**Comment by hackmanschorsch** [comment]
Now I found an example where it worked nicely when opening the first page. But when selecting a further page within the thumb overview then in the opened page is no selection of the first line made.

**Comment by hackmanschorsch** [comment]
And coming from the library to the view site the 'Edit' and 'Save changes' are disabled?

**Comment by cziaarm** [comment]
Hello all,

I would say here that the initial issue is satisfactorily resolved. 

@hackmanschorsch raises a the point that the page nav links (arrows and thumbnails) all reset the mode to view, but would be good if they opened the next page in the same mode (and if edit opened the edit for the first line on the new page)

The second point needs some support edit and save changes are working on the examples I've tried, give us some context! :)

I will close this one and raise a fresh one for the nav issue and Schorsch please check and elaborate on the edit/savechanges issue and raise a new one if it is persisting.

Cheers!
