### ISSUE TITLE
Fix image at top of canvas during zooming

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TWI-edit#60]
Otherwise the image disappears when zooming out

**Comment by kansallisarkisto** [comment]
This is not why the image disappears. However, zooming is limited as requested in #55 now and this problem should thus also be a thing of the past.

**Comment by hackmanschorsch** [comment]
But please have a look to Transkribus X (formerly known as expert client). There the image is fixed at the top left position during zooming and I think this is the most reasonable way. If the image goes down also the edit box gets shown at the bottom.

**Comment by hackmanschorsch** [comment]
Fix image to the top during zooming could be an option only for the buttons but not for the mouse wheel. Mouse wheel zooming works perfect but zooming with +/- could behave better.

**Comment by kansallisarkisto** [comment]
I stated in #63 that in my humble opinion the viewport centre was the most logical way to centre the image when zooming with buttons. I wrote that before reading this and testing the expert client zoom so I guess I can just as well push that version and then people can test and say what they like. Fit height is coming soon.

**Comment by hackmanschorsch** [comment]
This solution works fine.
