### ISSUE TITLE
Fit image to height

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TWI-edit#63]
Beside the 'Fit image to widht' also the 'Fit image to height' is a nice feature.
Fix image to the top during zooming could be an option only for the buttons but not for the mouse wheel. Mouse wheel zooming works perfect but zooming with +/- could behave better.

**Comment by kansallisarkisto** [comment]
What a coincidence. I just fixed an issue with mouse wheel zoom centering that nobody had noticed :b and came to think of how the image centre is an illogical centre for button zoom. It should be the viewport. Thus I'll make the change and add fit buttons.

**Comment by kansallisarkisto** [comment]
I've added a fit height button and changed the reset image button to a fit width button since that's what it effectively does. Would users prefer that the image y offset was kept and only x changed when the width is set to viewport width?

**Comment by GuenterMuehlberger** [comment]
For me it works fine as it is now .
