### ISSUE TITLE
Viewer LineByLine Scrolling not working on laptop

### ISSUE THREAD

**Issue by bejohu** [Transkribus/TWI-edit#67]
When cursor is above line image scrolling the page using touchpad mousewheel equivalent (i.e. running fingers vertically across trackpad) does not seem to work.

**Comment by jnphilipp** [comment]
Cannot reproduce, when scrolling images zoom in/out. What browser are you using?

**Comment by bejohu** [comment]
Seems to be fixed now. However, zooming without any special user action, e.g. ctrl key might lead to involuntary zooming. What do you think?

**Comment by cziaarm** [comment]
Ctrl is good idea, would need to communicate this to the user in some way

**Comment by bejohu** [comment]
If there are any +/- control elements that can be clicked, they could provide a tooltip spelling out the keyboard shortcuts. Most simple solution for this is probably setting the title attribute. Also, what's nice about it is that ctrl / meta + mousewheel / trackpad seems rather common for zooming, e.g. Photoshop, Firefox, etc. So, that's a plus in terms of discoverability. What seems most desireable is to zoom image only when mouse cursor is on top of it.
