### ISSUE TITLE
500 Internal server error when accessing some documents with edit app

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-edit#68]
OS and browser(s) [Windows 10]	Chrome
OS and browser(s) [Linux]	Firefox

URL: https://transkribus.eu/readTest/view/2305/4949/1

Screen shots : https://drive.google.com/open?id=0B7dmP0OCT3cnRmNFNkpmYV9xUzA

Steps to reproduce: 	Follow Url provided

Expected results and actual results :
Expected: edit/view for a document. Actual : "Server Error (500)" message

Any other information:	The Document IMAGES (4949) loads OK using the expert client and has 4 pages. Error on dev shows edit/templates/edit/correct.html, error at line 458

**Comment by jnphilipp** [comment]
Caused by documents with out lines.
