### ISSUE TITLE
Edit vs View mode

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TWI-edit#70]
Observed some strange behavior:
Steps to Reproduce: In library's document list click 'Image' (in the 'Views' row) to see the document in the edit page in 'View' mode - works fine
Now clicking Edit seems to provide the 'Edit' mode but it doesn't work.
Then clicking 'View' brings up the correct 'Edit' mode

But it works fine if you change to the edit page following the table link at the library instead of clicking on Views.

**Comment by jnphilipp** [comment]
This is a problem that has been solved, but it seems not it has not yet been deployed.
