### ISSUE TITLE
Box not widening with transcript line length

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-edit#72]
This looks like regression of the edit box width issue.

In this version the edit box does not widen when moving from an small or empty line to one with more text in it.

OS: Windows, linux
Browsers: chrome, ff

Steps to recreate:

https://transkribus.eu/readTest/edit/3/332/1

Tab from first line down to a line with some transcript in it.

Screenshot:

**Comment by kansallisarkisto** [comment]
I've noticed this and have fixed it locally already.
