### ISSUE TITLE
page nav should keep mode between pages

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-edit#73]
the page nav links (arrows and thumbnails) all reset the mode to view, but would be good if they opened the next page in the same mode (and if edit opened the edit for the first line on the new page)

**Comment by kansallisarkisto** [comment]
Couldn't agree more. But before implementing I want to ask if you too think that this is a user preference issue? I assume it should be handled as part of the preference saving implementation which is yet to be written.

**Comment by jnphilipp** [comment]
I cannot confirm this, as far as my test goes it works as expected. But it seems that the thumbnail view is broken in line by line and text interface.

**Comment by cziaarm** [comment]
Sorry poor description of what I meant.

We just need to pop up the edit box on the first line when moving pages

**Comment by hackmanschorsch** [comment]
minor bug: when changing pages (page nav) in edit mode in the line by line interface you can see for one moment the image view and shortly afterwards it changes into the line by line. As said a minor bug but maybe solved quickly?

**Comment by jnphilipp** [comment]
This is due to the image interface being the default interface and everything needs to be loaded before changing. I changed it so it wouldn't show on default. But I'm not sure what this might break, needs some serious testing.

**Comment by cziaarm** [comment]
I suggest that this is actually closed. we can raise another minor but in another iteration relating to the specific issue of the other view briefly appearing.
