### ISSUE TITLE
Text interface

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TWI-edit#76]
Show image snippet only after clicking the text line.

**Comment by hackmanschorsch** [comment]
This would be a feature needed for the user conference so that the users have the right impression even there is only the viewing mode available.

**Comment by hackmanschorsch** [comment]
Seems not to be in the deployed version.

**Comment by cziaarm** [comment]
reverted to Nathanael's last commit Transkribus/TWI-edit@981a239
