### ISSUE TITLE
404's from the logs

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-edit#78]
From the logs https://transkribus.eu/readTest/view/7290/24150/1 (which I can't view cos I don't have perms) is throwing an error becuase it is trying to get an image that is giving a 404 : https://dbis-thure.uibk.ac.at/f/Get?id=ZYBMUOMNJOQWALBJEJCTPMLV

[5:14] 
Also https://transkribus.eu/readTest/view/1/25238 is throwing an error because it is getting a 404 from a REST request: https://transkribus.eu/TrpServer/rest/collections/1/25238/1/curr

**Comment by cziaarm** [comment]
I have improved the handling of the 404 so that a sensible error message is shown rather than an apache 500.

The errors still remain.

**Comment by hackmanschorsch** [comment]
Seems that doc 25238 was deleted in collection 1. So this is the reason for the 404. We could try to send more meaningful responses? 
I have viewed https://transkribus.eu/readTest/view/7290/24150/1 and it works well. The image link must be from somewhere else.
So how should we react on such 404 errors?

**Comment by cziaarm** [comment]
404's are genuine (ie the resources are not on the server)

and 404's are being better handled by webUI
