### ISSUE TITLE
Colors in thumb overview

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TWI-edit#81]
Use similar coloring as in TranskribusX.
Red: No segmentation available (nr_of_lines  == 0)
Yellow: Segmented lines are there - but no text. (nr_of_lines > 0 && nr_of_transcribed_lines == 0)
Green: Lines with text are available (nr_of_transcribed_lines > 0)

**Comment by kansallisarkisto** [comment]
This was pretty low hanging fruit so I've implemented it now.
