### ISSUE TITLE
Turn the page bug

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TWI-edit#82]
If you are in edit mode (Image or line by line) and go to the next page (with arrow) then you stay in edit mode but all interfaces are active now (side by side and Text). You can then edit in side by side (which you should not see in edit mode) but not in line by line (which should work)

**Comment by cziaarm** [comment]
Hi @hackmanschorsch I'm seeing slightly different behaviour at the moment.

It seems that if you are in image/edit mode and then click on the next button you are returned to view mode.

Which is annoying (and possibly a regression), but the user doesn't have a route to edit in sbs and text that I can see. Please confirm this, or explain what I'm doing wrong in terms of replicating this bug.

**Comment by hackmanschorsch** [comment]
Hi, I tested it now on Chrome as well. The strange thing is that if I start at the first page - click edit - then click next - I stay in the edit mode with all interfaces enabled. If I then go to the next page it is like you described (a change to view mode)

**Comment by hackmanschorsch** [comment]
Minor update: The first next click gives the described behavior regardless of which page number I start.

**Comment by cziaarm** [comment]
I was looking at this doc btw: https://transkribus.eu/readTest/view/2305/23315

**Comment by jnphilipp** [comment]
@cziaarm that you are no longer in edit mode when going to the next page isn't most likely a bug, resulting from a wrong link but the result of the various checks that are done upon page load. Like I mentioned yesterday in the call a page which has GT page status can't be edited and so a user is redirected back to view mode. In the log should be an entry of that.

I'm thinking it would be best to show page status regardless of edit/view mode, but make it only editable in edit mode.

**Comment by jnphilipp** [comment]
@hackmanschorsch I'll have a look at what happens there.

**Comment by cziaarm** [comment]
@hackmanschorsch you said: "The first next click gives the described behavior" whcih described behaviour (mine or yours). Maybe the collection/document is important here I have some odd behaviour around the page status which may cause some of what we're seeing

**Comment by hackmanschorsch** [comment]
I meant 'mine'.
It really depends on the document. The one you sent brought the same behavior for me as on your side.

**Comment by cziaarm** [comment]
@jnphilipp yes I'm beginning to understand this. However if you go to the example I've given and do the following:

- Starting on image mode (edit button enabled)
- Click on next page (edit button still enabled)
- Click on a restricted interface (edit button correctly disabled)
- Click on image interface again (edit button remains disabled)

Cheers,

Rory

**Comment by hackmanschorsch** [comment]
But may the save bug Günter mentioned is at the moment more important to solve?

**Comment by jnphilipp** [comment]
@cziaarm The second page is GT so the edit button should be disabled from the beginning.

**Comment by cziaarm** [comment]
@jnphilipp aha.. I see so the bug is that the edit button appeared at all?

 I thought you were on holiday... are you looking at this stuff at the moment? I wouldn't want to cause a code conflict, and you may be better placed to solve this than I  (though it was interesting to catch-up with where the edit code is at the moment)

**Comment by jnphilipp** [comment]
Yeah I'm on holiday, or better sitting at home and doing same coding on other stuff. So i hat just a quick look. If you want me to take a closer look no problem.

**Comment by cziaarm** [comment]
I'm happy to continue (especially if you are on holiday) I may check in with you when I think I have solution to check it makes sense

**Comment by cziaarm** [comment]
OK I think I've fixed "my" bug @hackmanschorsch if you can give me an example url I can have a go at yours too

**Comment by jnphilipp** [comment]
@cziaarm Have a look at what i pushed it should fix @hackmanschorsch bug.

**Comment by hackmanschorsch** [comment]
I dulicate the document to the WebUI Collection at the moment. It is called 'Reichsgericht I.-ZvS_1903_2.+3.Q_duplicated'. Should be available in a few seconds.

**Comment by hackmanschorsch** [comment]
Page status is 'Done' btw for that pages

**Comment by cziaarm** [comment]
Thanks both,

I've just deployed @jnphilipp's fix for @hackmanschorsch's bug and @cziaarm's fix for @cziaarm's bug.

To test bug one : https://transkribus.eu/readTest/edit/2305/28650 , edit > got to next page, restricted interfaces should stay disabled for editing

To test bug two: https://transkribus.eu/readTest/view/2305/23315 , got to page 2, edit button should be disabled (it's GT)

Thanks!
