### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TWI-edit#84]
Tagging brings sometimes unreproducible errors, e.g. all tags are selected in the context box or text is tagged that wasn't marked
So we should do two things: 

1. No tagging in the Image view. Should make things easier for Matti - no multiline selection for example.
2. Tagging allowed only in line by line for the first release

**Comment by cziaarm** [comment]
Matti's solution should alleviate tagging issues.

**Comment by cziaarm** [comment]
Line by line has been turned off for first release
