### ISSUE TITLE
Add button to resize edit box 

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TWI-edit#85]
If the edit box grows larger then the size of the screen there are limited possibilities to resize it. A button would be therefore nice to have. And pressing this button modifies the size of the edit box with respect to the current text line.

**Comment by cziaarm** [comment]
- [x] Turn off the thing that stops the user moving the dialog out of the window
- [x] This allows users to move the dialog if it is bigger than the window
- [ ]  Clicking on line on image will re-shrink the dialog relative to line length

**Comment by cziaarm** [comment]
Only last of these three not implemented

**Comment by kansallisarkisto** [comment]
As far as I can tell the third one doesn't happen anymore or have I misunderstood what the problem is?

**Comment by kansallisarkisto** [comment]
I should add that I've now prevented the dialog from becoming wider than the window.
