### ISSUE TITLE
Remove characters reapear in correctModal.

### ISSUE THREAD

**Issue by jnphilipp** [Transkribus/TWI-edit#9]
Removed characters reappear after entering a new character in the input dialog (correctModal). Observed using Chromium/qutebrowser (QtWebEngine).

**Comment by jnphilipp** [comment]
Still persists.

**Comment by jnphilipp** [comment]
Nach some investigating, chrome doesn't trigger a keypress event when pressing backspace. Same is true for del.

**Comment by kansallisarkisto** [comment]
I have rewritten it without using keypress. Will commit soon.
